export const UPDATE_DASHBOARD_TAB_INDEX = 'UPDATE_DASHBOARD_TAB_INDEX'

export const POPULATE_CONTACT_MESSAGES = 'POPULATE_CONTACT_MESSAGES'
export const CLEAR_CONTACT_MESSAGES = 'CLEAR_CONTACT_MESSAGES'
